### ISSUE TITLE
Automatically launch signal-cli when the daemon is launched

### ISSUE THREAD

**Issue by thefinn93** [thefinn93/signal-weechat#3]
Currently we require signal-cli to be launched and managed separately, which is kinda shitty

**Comment by anarcat** [comment]
i still have to start the daemon by hand here, otherwise i get this:

```
11:56:53 python : stdout/stderr : Traceback (most recent call last):
11:56:53 python : stdout/stderr :   File "/home/anarcat/.weechat/python/signal.py", line 115, in send
11:56:53 python : stdout/stderr :     getSignal().sendMessage(message, dbus.Array(signature="s"), number)
11:56:53 python : stdout/stderr :   File "/home/anarcat/.weechat/python/signal.py", line 105, in getSignal
11:56:53 python : stdout/stderr :     return bus.get_object('org.asamk.Signal', '/org/asamk/Signal')      
11:56:53 python : stdout/stderr :   File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
11:56:53 python : stdout/stderr :     follow_name_owner_changes=follow_name_owner_changes)                      
11:56:53 python : stdout/stderr :   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
11:56:53 python : stdout/stderr :     self._named_service = conn.activate_name_owner(bus_name)                    
11:56:53 python : stdout/stderr :   File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
11:56:53 python : stdout/stderr :     self.start_service_by_name(bus_name)                                               
11:56:53 python : stdout/stderr :   File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
11:56:53 python : stdout/stderr :     'su', (bus_name, flags)))                                                            
11:56:53 python : stdout/stderr :   File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
11:56:53 python : stdout/stderr :     message, timeout)                                                                   
11:56:53 python : stdout/stderr : dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.asamk.Signal was not provided by any .service
         files
```

it looks like the daemon is started correctly when you register or link, but there's nothing to start the daemon when weechat restarts on its own.

**Comment by thefinn93** [comment]
Interesting. Is there anything in the debug file? The weechat plugin launches a python daemon, which launches the signal-cli daemon and passes messages from it back to weechat (which can't listen to dbus directly). Try launching the python daemon manually and see if that's the problem.

**Comment by tych0** [comment]
I'm gonna close this since we're on the signald branch.
